# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GifMaker < Formula
  desc ""
  homepage "https://github.com/theIYD/go-gif-maker"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/theIYD/go-gif-maker/releases/download/v0.1.1/gif-maker_Darwin_arm64.tar.gz"
      sha256 "f77592b00ba2c7c3b1c71c890f3adbe698d6c40f7607e2a2e881bf81f60d6984"

      def install
        bin.install "gif-maker"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/theIYD/go-gif-maker/releases/download/v0.1.1/gif-maker_Darwin_x86_64.tar.gz"
      sha256 "f5153640d03caba4a41db2edfd2250aad265410beda46f7bb129754faecf952e"

      def install
        bin.install "gif-maker"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/theIYD/go-gif-maker/releases/download/v0.1.1/gif-maker_Linux_arm64.tar.gz"
      sha256 "690d8ab4189e4aac5857a6af3723e4b6cfb2d410abfe439b539fcb1eb6475ac5"

      def install
        bin.install "gif-maker"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/theIYD/go-gif-maker/releases/download/v0.1.1/gif-maker_Linux_x86_64.tar.gz"
      sha256 "16d7bfd9c99b47483410f7bbc6a1f9595f627bc7b5276eb1424acbc50d8ffefe"

      def install
        bin.install "gif-maker"
      end
    end
  end
end
